Repository onepercentclub/bluebottle, pull requests merged in 2018-10, with the labels that each got.

#3361 Upgrade Flutterwave to v2 api
  setup.py
Labels: do not merge

#3414 Validate that tasks for projects with a duration are within the duration
  bluebottle/tasks/serializers.py
  bluebottle/tasks/tests/test_api.py
Labels: Needs more work

#3386 Add all reviewers to project filter
  bluebottle/projects/admin.py
  bluebottle/projects/tests/test_admin.py
Labels: testing for release

#3384 Show "Anonymous user" instead of an empty name in donation export view
  bluebottle/bb_orders/models.py
  bluebottle/projects/tests/test_api.py
  bluebottle/projects/views.py
Labels: testing for release

#3383 Account holder name cannot be longer then 100 characters.
  bluebottle/bb_projects/models.py
  bluebottle/projects/migrations/0080_auto_20180828_1522.py
Labels: testing for release

#3409 Online / on location filter should filter both null and blank fields.
  bluebottle/tasks/admin.py
  bluebottle/tasks/tests/test_admin.py
Labels: needs testing :vertical_traffic_light:
