Repository onepercentclub/bluebottle, pull requests merged in 2019-02, with the labels that each got.

#3392 Hotfix/csrf token in session
  bluebottle/auth/views.py
  bluebottle/clients/postgresql_backend/base.py
  bluebottle/clients/tests/test_api.py
  bluebottle/looker/migrations/0003_init_looker_embeds.py
  bluebottle/projects/admin.py
  bluebottle/projects/migrations/0007_project_currencies.py
  bluebottle/projects/migrations/0011_auto_20161006_1149.py
  bluebottle/projects/migrations/0014_auto_20161109_1041.py
  bluebottle/projects/migrations/0014_auto_20161115_1601.py
  bluebottle/projects/migrations/0015_auto_20161207_0900.py
  bluebottle/projects/migrations/0019_auto_20170106_1657.py
  bluebottle/projects/migrations/0043_auto_20171023_1958.py
  bluebottle/projects/migrations/0048_auto_20171024_1052.py
  bluebottle/projects/migrations/0072_auto_20180416_1115.py
  bluebottle/projects/migrations/0078_auto_20180528_1414.py
  bluebottle/projects/migrations/0080_auto_20180904_1532.py
  bluebottle/projects/migrations/0081_merge_20180911_1659.py
  bluebottle/projects/models.py
  bluebottle/projects/tests/test_admin.py
  bluebottle/projects/tests/test_api.py
  bluebottle/settings/base.py
  bluebottle/social/tests/test_api.py
  bluebottle/social/views.py
  bluebottle/urls/core.py
  bluebottle/utils/email_backend.py
  bluebottle/utils/widgets.py
  setup.py
Labels: security

#3497 Do not store country of payout account, instead we use the value from
  bluebottle/payouts/migrations/0022_auto_20190211_1452.py
  bluebottle/payouts/models.py
  bluebottle/payouts/serializers.py
  bluebottle/payouts/tests/test_api.py
Labels: bug, needs testing :vertical_traffic_light:

#3490 Change recipient to initiator in donation confirmation email.
  bluebottle/donations/templates/donations/mails/payment_details.html
  bluebottle/donations/templates/donations/mails/payment_details.txt
  bluebottle/payments_pledge/templates/payments_pledge/mails/pledge_details.mail.html
  bluebottle/payments_pledge/templates/payments_pledge/mails/pledge_details.mail.txt
  bluebottle/payments_stripe/models.py
  bluebottle/payments_stripe/tests/test_adapters.py
Labels: needs testing :vertical_traffic_light:

#3502 Allow blank country on payout account
  bluebottle/payouts/serializers.py
Labels: needs testing :vertical_traffic_light:

#3500 Feature/security fixes
  bluebottle/auth/views.py
  bluebottle/bb_accounts/urls/api.py
  bluebottle/bb_accounts/views.py
  bluebottle/categories/migrations/0006_auto_20180907_1131.py
  bluebottle/categories/migrations/0007_auto_20180907_1131.py
  bluebottle/categories/models.py
  bluebottle/categories/views.py
  bluebottle/clients/postgresql_backend/base.py
  bluebottle/clients/tests/test_api.py
  bluebottle/looker/migrations/0003_init_looker_embeds.py
  bluebottle/members/migrations/0017_closed_site_permissions.py
  bluebottle/members/migrations/0026_auto_20180919_1434.py
  bluebottle/members/migrations/0028_merge_20190215_1441.py
  bluebottle/members/models.py
  bluebottle/members/tests/test_api.py
  bluebottle/members/utils.py
  bluebottle/projects/admin.py
  bluebottle/projects/migrations/0007_project_currencies.py
  bluebottle/projects/migrations/0011_auto_20161006_1149.py
  bluebottle/projects/migrations/0014_auto_20161109_1041.py
  bluebottle/projects/migrations/0014_auto_20161115_1601.py
  bluebottle/projects/migrations/0015_auto_20161207_0900.py
  bluebottle/projects/migrations/0019_auto_20170106_1657.py
  bluebottle/projects/migrations/0043_auto_20171023_1958.py
  bluebottle/projects/migrations/0048_auto_20171024_1052.py
  bluebottle/projects/migrations/0072_auto_20180416_1115.py
  bluebottle/projects/migrations/0078_auto_20180528_1414.py
  bluebottle/projects/migrations/0080_auto_20180904_1532.py
  bluebottle/projects/migrations/0081_auto_20180918_1335.py
  bluebottle/projects/migrations/0081_merge_20180911_1659.py
  bluebottle/projects/migrations/0087_merge_20190206_1714.py
  bluebottle/projects/migrations/0088_merge_20190208_1523.py
  bluebottle/projects/migrations/0088_merge_20190215_1425.py
  bluebottle/projects/migrations/0089_merge_20190215_1438.py
  bluebottle/projects/models.py
  bluebottle/projects/tests/test_admin.py
  bluebottle/projects/tests/test_api.py
  bluebottle/scim/tests/test_admin.py
  bluebottle/settings/base.py
  bluebottle/social/tests/test_api.py
  bluebottle/social/views.py
  bluebottle/terms/migrations/0002_auto_20180907_1132.py
  bluebottle/terms/migrations/0003_auto_20180907_1132.py
  bluebottle/terms/models.py
  bluebottle/terms/views.py
  bluebottle/urls/core.py
  bluebottle/utils/email_backend.py
  bluebottle/utils/templates/django/forms/widgets/input_option.html
  bluebottle/utils/views.py
  bluebottle/utils/widgets.py
  bluebottle/wallposts/models.py
  bluebottle/wallposts/permissions.py
  bluebottle/wallposts/serializers.py
  bluebottle/wallposts/tests/test_api.py
  bluebottle/wallposts/urls/api.py
  bluebottle/wallposts/views.py
  setup.py
Labels: needs testing :vertical_traffic_light:, security

#3410 Feature/set email using password
  bluebottle/bb_accounts/urls/api.py
  bluebottle/bb_accounts/views.py
  bluebottle/members/serializers.py
  bluebottle/members/tests/test_api.py
  bluebottle/projects/migrations/0086_merge_20190204_1005.py
  bluebottle/projects/migrations/0088_merge_20190213_1448.py
  bluebottle/projects/migrations/0090_merge_20190222_1101.py
  setup.py
Labels: needs testing :vertical_traffic_light:, security

#3411 Make the fundraiser image not required. This makes it possible to edit
  bluebottle/fundraisers/serializers.py
Labels: needs testing :vertical_traffic_light:
