Repository onepercentclub/bluebottle, pull requests merged in 2019-03, with the labels that each got.

#3509 Set payment-descriptor for stripe payments
  bluebottle/payments_stripe/adapters.py
Labels: needs testing :vertical_traffic_light:

#3523 Donation admin tests
  bluebottle/donations/tests/test_admin.py
  bluebottle/payments_mock/models.py
  bluebottle/test/factory_models/payments.py
Labels: cleanup :hammer_and_wrench:

#3522 Tests for Beyonic adapter
  bluebottle/payments_beyonic/tests/__init__.py
  bluebottle/payments_beyonic/tests/test_adapters.py
Labels: cleanup :hammer_and_wrench:

#3517 Settings for parallel migrations
  bluebottle/settings/base.py
Labels: cleanup :hammer_and_wrench:

#3513 Improve donation export and Lipisha admin
  bluebottle/donations/management/commands/export_donations.py
  bluebottle/donations/tests/test_exports.py
  bluebottle/payments/models.py
  bluebottle/payments_lipisha/admin.py
Labels: cleanup :hammer_and_wrench:

#3512 remove bb_*
  bluebottle/bb_follow/models.py
  bluebottle/bb_fundraisers/models.py
  bluebottle/bb_fundraisers/tests/__init__.py
  bluebottle/bb_fundraisers/urls/__init__.py
  bluebottle/bb_metrics/models.py
  bluebottle/bb_metrics/signals.py
  bluebottle/bb_metrics/tests/__init__.py
  bluebottle/bb_metrics/tests/test_unit.py
  bluebottle/bb_metrics/utils.py
  bluebottle/bb_orders/__init__.py
  bluebottle/bb_orders/models.py
  bluebottle/bb_orders/signals.py
  bluebottle/bb_orders/tests/__init__.py
  bluebottle/bb_orders/urls/__init__.py
  bluebottle/common/tests/test_api.py
  bluebottle/donations/tests/test_api.py
  bluebottle/donations/views.py
  bluebottle/fundraisers/models.py
  bluebottle/fundraisers/static/images/fundraisers/default-picture.png
  bluebottle/fundraisers/templates/generic/form_charfield.html
  bluebottle/fundraisers/templates/generic/form_field.html
  bluebottle/fundraisers/templates/generic/form_imagefield.html
  bluebottle/fundraisers/tests/images/upload.png
  bluebottle/fundraisers/tests/test_api.py
  bluebottle/fundraisers/urls/__init__.py
  bluebottle/fundraisers/urls/api.py
  bluebottle/fundraisers/views.py
  bluebottle/orders/models.py
  bluebottle/orders/permissions.py
  bluebottle/orders/signals.py
  bluebottle/orders/tests/test_api.py
  bluebottle/orders/tests/test_models.py
  bluebottle/orders/urls/__init__.py
  bluebottle/orders/urls/api.py
  bluebottle/orders/views.py
  bluebottle/payments/tests/test_api.py
  bluebottle/payments/views.py
  bluebottle/projects/models.py
  bluebottle/settings/base.py
  bluebottle/urls/core.py
Labels: cleanup :hammer_and_wrench:

#3533 Make sure that if no payout account is set we also trigger a validati…
  bluebottle/projects/admin.py
  bluebottle/projects/tests/test_admin.py
Labels: Needs more work
