Repository onepercentclub/bluebottle, pull requests merged in 2022-03, with the labels that each got.

#4958 🚀 Mandatory Profile Questions
  bluebottle/bb_accounts/models.py
  bluebottle/bb_accounts/tests/test_api.py
  bluebottle/bluebottle_dashboard/static/admin/images/icons/info.svg
  bluebottle/bluebottle_dashboard/static/jet/css/_messages.scss
  bluebottle/bluebottle_dashboard/static/jet/css/themes/goodup/base.css
  bluebottle/bluebottle_dashboard/static/jet/css/themes/goodup/base.css.map
  bluebottle/bluebottle_dashboard/static/jet/how-to.txt
  bluebottle/bluebottle_dashboard/static/jet/package.json
  bluebottle/bluebottle_dashboard/static/jet/yarn.lock
  bluebottle/clients/tests/test_api.py
  bluebottle/members/admin.py
  bluebottle/members/migrations/0051_auto_20220215_1521.py
  bluebottle/members/migrations/0052_auto_20220215_1538.py
  bluebottle/members/migrations/0053_auto_20220221_1434.py
  bluebottle/members/migrations/0054_auto_20220225_1344.py
  bluebottle/members/migrations/0054_auto_20220301_1336.py
  bluebottle/members/migrations/0055_auto_20220301_1336.py
  bluebottle/members/migrations/0056_merge_20220301_1627.py
  bluebottle/members/models.py
  bluebottle/members/serializers.py
  bluebottle/members/tests/test_admin.py
  bluebottle/members/tests/test_api.py
  bluebottle/segments/admin.py
  bluebottle/segments/migrations/0025_segmenttype_required.py
  bluebottle/segments/migrations/0026_auto_20220215_1521.py
  bluebottle/segments/models.py
  bluebottle/segments/serializers.py
  bluebottle/segments/templates/segments/admin/required_segment_types.html
  bluebottle/segments/templates/widgets/segment-select.html
  bluebottle/segments/tests/factories.py
  bluebottle/segments/tests/test_admin.py
  bluebottle/token_auth/auth/base.py
  bluebottle/token_auth/tests/test_base.py
Labels: 🚀 Feature Release

#5010 Add team model. Create team for contributor and add contributor to team
  .travis.yml
  bluebottle/activities/admin.py
  bluebottle/activities/effects.py
  bluebottle/activities/migrations/0047_auto_20220321_1428.py
  bluebottle/activities/migrations/0048_contributor_team.py
  bluebottle/activities/models.py
  bluebottle/activities/templates/admin/create_team.html
  bluebottle/collect/tests/test_triggers.py
  bluebottle/collect/triggers.py
  bluebottle/deeds/tests/test_triggers.py
  bluebottle/deeds/triggers.py
  bluebottle/time_based/tests/test_triggers.py
  bluebottle/time_based/triggers.py
Labels: do not merge

#4994 Release Team Activities
  bluebottle/activities/admin.py
  bluebottle/activities/documents.py
  bluebottle/activities/filters.py
  bluebottle/activities/migrations/0046_auto_20220317_0900.py
  bluebottle/activities/models.py
  bluebottle/activities/tests/test_api.py
  bluebottle/activities/utils.py
  bluebottle/clients/tests/test_api.py
  bluebottle/collect/admin.py
  bluebottle/deeds/admin.py
  bluebottle/funding/admin.py
  bluebottle/initiatives/admin.py
  bluebottle/initiatives/migrations/0039_auto_20220316_1253.py
  bluebottle/initiatives/models.py
  bluebottle/initiatives/serializers.py
  bluebottle/initiatives/tests/test_admin.py
  bluebottle/notifications/tests/locale/en/LC_MESSAGES/django.po
  bluebottle/notifications/tests/locale/fr/LC_MESSAGES/django.po
  bluebottle/notifications/tests/locale/nl/LC_MESSAGES/django.po
  bluebottle/time_based/admin.py
  bluebottle/time_based/models.py
  bluebottle/time_based/tests/test_admin.py
  bluebottle/time_based/tests/test_scenarios.py
  locale/en/LC_MESSAGES/django.po
  locale/fr/LC_MESSAGES/django.po
  locale/nl/LC_MESSAGES/django.po
Labels: do not merge, 🚀 Feature Release
